branches:
  only:
    - master
gemfile:
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 2.5.7
  - ruby-head
script: bundle exec rspec
